---


- name: Create portainer storage  
  file:
    path: "{{ portainer_storage_directory }}"
    state: directory

- block:

  - name: Start Portainer
    docker_container: 
      image: "{{ portainer_image_name }}"
      state: started
      name: "{{ portainer_container_name }}"
      restart_policy: unless-stopped
      volumes:
        - "{{ portainer_storage_directory }}:/data"
        - "/var/run/docker.sock:/var/run/docker.sock"
      published_ports:
        - "127.0.0.1:9000:9000"

  when:
    - env == "production"

- block:

  - name: Edit firewalld for Portainer port
    firewalld:
      port: "{{ portainer_publish_port }}/tcp"
      permanent: true
      state: enabled
    notify: restart firewalld

  - name: Start Portainer
    docker_container: 
      image: "{{ portainer_image_name }}"
      state: started
      name: "{{ portainer_container_name }}"
      restart_policy: unless-stopped
      volumes:
        - "{{ portainer_storage_directory }}:/data"
        - "/var/run/docker.sock:/var/run/docker.sock"
      published_ports:
        - "{{ portainer_publish_port }}:9000"

  when:
    - env == "develop"